// Code generated by entc, DO NOT EDIT.

package ent

import (
	"imdb-movie/ent/movie"
	"imdb-movie/ent/schema"
	"imdb-movie/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	movieFields := schema.Movie{}.Fields()
	_ = movieFields
	// movieDescRealeaseDate is the schema descriptor for realease_date field.
	movieDescRealeaseDate := movieFields[2].Descriptor()
	// movie.DefaultRealeaseDate holds the default value on creation for the realease_date field.
	movie.DefaultRealeaseDate = movieDescRealeaseDate.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
}
