// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Movie is the predicate function for movie builders.
type Movie func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
